1. Transpose

In [2]:
import numpy as np

In [4]:
vector = np.array([[1,2,3,4,5,6]])
matrix = np.array([[1,2,3],[4,5,6]])

print(vector)

print(vector.T)

print(matrix)

print(matrix.T)

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


2. Identity Matrix 

In [5]:
A = np.array([[1,2],[3,4]])
I = np.identity(2, dtype=int)

print("I: \n",I)
print()
print("AI: \n", np.dot(A, I))
print()
print("A: \n", A)

I: 
 [[1 0]
 [0 1]]

AI: 
 [[1 2]
 [3 4]]

A: 
 [[1 2]
 [3 4]]


3. Inverse Matrix

In [8]:
A = np.array([[1,2],[3,4]])

print("A: \n",A)
print()
print("inverse of A  is : \n", np.linalg.inv(A))

#test
Ainv = np.linalg.inv(A)
print(np.matmul(A,Ainv))

A: 
 [[1 2]
 [3 4]]

inverse of A  is : 
 [[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
