1. Transpose

In [2]:
import numpy as np

In [4]:
vector = np.array([[1,2,3,4,5,6]])
matrix = np.array([[1,2,3],[4,5,6]])

print(vector)

print(vector.T)

print(matrix)

print(matrix.T)

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


2. Identity Matrix 

In [5]:
A = np.array([[1,2],[3,4]])
I = np.identity(2, dtype=int)

print("I: \n",I)
print()
print("AI: \n", np.dot(A, I))
print()
print("A: \n", A)

I: 
 [[1 0]
 [0 1]]

AI: 
 [[1 2]
 [3 4]]

A: 
 [[1 2]
 [3 4]]
