In [7]:
import numpy as np

a = np.array([1,2,3])
print(a)



[1 2 3]


In [8]:
b= np.arange(3)
print(b)

[0 1 2]


In [9]:
c = np.arange(1, 20 ,3)
print(c)

[ 1  4  7 10 13 16 19]


In [10]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]
