In [2]:
import numpy as np

a = np.array([1,2,3])
print(a)



[1 2 3]


1.Initial With Arrays

In [8]:
b= np.arange(3)
print(b)

[0 1 2]


In [9]:
c = np.arange(1, 20 ,3)
print(c)

[ 1  4  7 10 13 16 19]


In [10]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


In [11]:
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [12]:
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [13]:
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [14]:
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [15]:
rand_arr = np.random.rand(3)
print(rand_arr)

[0.03356087 0.42180521 0.89748386]


2.Multidimentional Arrays

In [16]:
two_dim_arr = np.array([[1,2,3],[4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [19]:
# 1-D array
one_dim_arr = np.array([1,2,3,4,5,6])

# Multidimentional Array Using reshape()
multi_dim_arr = np.reshape(one_dim_arr,(2,3))

#print the new 2-D array with tow rows and three columns
print(multi_dim_arr)


[[1 2 3]
 [4 5 6]]


2.1. Finding size, shape and dimention.

In [20]:
multi_dim_arr.ndim

2

In [21]:
multi_dim_arr.shape

(2, 3)

In [22]:
multi_dim_arr.size

6

3.Array Math operations

In [25]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([3,4,5])

#Adding
addition = arr_1 + arr_2
print(addition)

#Subtracting
subtraction = arr_1 - arr_2
print(subtraction)

#Multiplying
multiplying = arr_1 * arr_2
print(multiplying) 

[4 6 8]
[-2 -2 -2]
[ 3  8 15]


3.1.Multiplying vextors with a scalar (broadcasting)

In [26]:
vector = np.array([1,2])
vector*2

array([2, 4])

4.Indexing and slicing

4.1.Indexing

In [27]:
a= ([1,2,3,4,5])
print(a[2])

3


In [28]:
two_dim = np.array(([1,2,3],[4,5,6],[7,8,9]))

print(two_dim[2][1])

8


4.2.Slicing

In [30]:
sliced_arr = a[1:4]
print(sliced_arr)

[2, 3, 4]


In [31]:
sliced_arr = a[:3]
print(sliced_arr)

[1, 2, 3]


In [33]:
sliced_arr = a[2:]
print(sliced_arr)

[3, 4, 5]


In [35]:
sliced_arr = a[::2]
print(sliced_arr)

[1, 3, 5]


In [36]:
sliced_arr_1 = two_dim[0:2]
sliced_arr_1

array([[1, 2, 3],
       [4, 5, 6]])

5.Stacking

In [39]:
a1 = np.array([[1,1],[2,2]])

a2 = np.array([[3,3],[4,4]])

vert_stack = np.vstack((a1,a2))

horz_stack = np.hstack((a1,a2))

print(vert_stack)

print(horz_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


6. System of Linear Equations

6.1. Solving Systems of Linear Equations using Matrices

In [4]:
a = np.array([[-1,3],[3,2]],dtype=np.dtype(float))

b = np.array([7,1],dtype=np.dtype(float))

print("Martix A:")
print(a)
print("\nMatrix B:")
print(b)

#ُSolving
x = np.linalg.solve(a, b)
print("resault:" , x)

Martix A:
[[-1.  3.]
 [ 3.  2.]]

Matrix B:
[7. 1.]
resault: [-1.  2.]


6.2 Evaluating Deteminant of a Matrices

In [5]:
d = np.linalg.det(a)

print("Determinant of matrix a :", d)

Determinant of matrix a : -11.000000000000002


7. System of Linear Equations with No Solutions

In [7]:
a_2 = np.array([[-1,3],[3,-9]],dtype=np.dtype(float))

b_2 = np.array([7, 1], dtype=np.dtype(float))

d_2 = np.linalg.det(a_2)

print("Determinant of matrix a_2 :", d_2)

Determinant of matrix a_2 : 0.0


In [8]:
try:
  x_2 = np.linalg.solve(a_2, b_2)
except np.linalg.LinAlgError as err:
  print(err)

Singular matrix


Some Examples


In [16]:
a_3 = np.array([[1,1,1],[1,1,2],[1,1,3]],dtype=np.dtype(float))

b_3 = np.array([10,15,18], dtype=np.dtype(float))

d_3 = np.linalg.det(a_3)

print(d_3)

try:
  x_3 = np.linalg.solve(a_3, b_3)
except np.linalg.LinAlgError as err:
  print(err)


0.0
Singular matrix
